@echo off
if defined GHOSTSHELL_CLAUDE_SHIM_DIRECTORY (
  for %%I in (claude.cmd) do set "GHOSTSHELL_CLAUDE_CURRENT=%%~$PATH:I"
  if /I not "%GHOSTSHELL_CLAUDE_CURRENT%"=="%GHOSTSHELL_CLAUDE_SHIM_DIRECTORY%\claude.cmd" (
    set "PATH=%GHOSTSHELL_CLAUDE_SHIM_DIRECTORY%;%PATH%"
  )
  set "GHOSTSHELL_CLAUDE_CURRENT="
)
