version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 10
    rebase-strategy: auto

  - package-ecosystem: nuget
    directory: /vendor/exclr8cef
    schedule:
      interval: weekly
      day: monday
      time: "04:15"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 5
    rebase-strategy: auto

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 10
    rebase-strategy: auto
