<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GhostShell.App\GhostShell.App.csproj" />
    <ProjectReference Include="..\..\src\GhostShell.Databases\GhostShell.Databases.csproj" />
    <ProjectReference Include="..\..\src\GhostShell.Infrastructure\GhostShell.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\GhostShell.Redis\GhostShell.Redis.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
