<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentIcons.Avalonia" Version="2.1.333" />
    <ProjectReference Include="..\GhostShell.Application\GhostShell.Application.csproj" />
    <ProjectReference Include="..\..\vendor\exclr8cef\src\Exclr8Cef.WebView\Exclr8Cef.WebView.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GhostShell" />
    <InternalsVisibleTo Include="GhostShell.Browser.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
