<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GhostShell.Core\GhostShell.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GhostShell.Application.Tests" />
    <InternalsVisibleTo Include="GhostShell.Infrastructure.Tests" />
    <InternalsVisibleTo Include="GhostShell.SessionHost.Tests" />
    <InternalsVisibleTo Include="GhostShell.Terminal" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
