<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GhostShell.Application\GhostShell.Application.csproj" />
    <ProjectReference Include="..\GhostShell.Core\GhostShell.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GhostShell.Infrastructure.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="SQLite3MC.PCLRaw.bundle" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
